### PR TITLE
Updated the styles of the about page and the bottomNavBar and added a new BottomNavBar.css file

### PR DESCRIPTION
**Pull request by Harry101969**

### CODE REVIEW

**Review by Harry101969 — COMMENTED** [review]
Updated the styles of the about page

**Comment by MohitGupta12** [comment]
harsh can you remove harsh.txt from this PR and have you checked those commit cause is it necessary to add about-tag when it doesn't have any css property attached to it

**Comment by Harry101969** [comment]
Actually I added some different styles which were required to correct the applications style associated with the bottomNavBar. And talking about the about-tag it does have a css property associated to it and as a result is needed. Also I've removed the text file as well

**Review by MohitGupta12 — APPROVED** [review]
This is good i'll merge it

**Pull request merged**
